= Asciidoc syntax cheat sheet 
:author: Yuri Slobodyanyuk

Author: Yuri Slobodyanyuk, admin@yurisk.info

[cols=2,options="header"]
|===

|Command
|Description


|`article, book, manpage`
|Types of AsciiDoc documents

|Block types
a| Document ::= (Header?, Preamble?, Section*) +
        Header ::= (Title, (AuthorInfo, RevisionInfo?)?) +
        AuthorInfo ::= (FirstName, (MiddleName?, LastName?)?, EmailAddress?) +
        RevisionInfo ::= (RevisionNumber?, RevisionDate, RevisionRemark?) +
        Preamble ::= (SectionBody) +
        SectionBody ::= ((BlockTitle?, Block) \| (BlockMacro)+ + 
        Block ::= (Paragraph \| DelimitedBlock \| List \| Table) +
        List ::= (BulletedList \| NumberedList \| LabeledList \| CalloutList) +
        BulletedList ::= (ListItem)+ +
        NumberedList ::= (ListItem)+ +
        CalloutList ::= (ListItem)+ +
        LabeledList ::= (ListItem)+ +
        ListEntry ::= (ListLabel, ListItem) +
        ListLabel ::= (ListTerm+) +
        ListItem ::= (ItemText, (List \| ListParagraph \| ListContinuation)*) 

|'text' or  \_text_
|_text_ will be in italics.










|===
