= Aruba HP switches configuration examples cookbook
Yuri SLobodyanyuk, admin@yurisk.info
:homepage: https://yurisk.info
:toc:

Author: Yuri Slobodyanyuk,  https://www.linkedin.com/in/yurislobodyanyuk/


== Reset/wipe switch configuration to the factory defaults
WARNING: This will erase all the configuration and cannot be undone.

If you don't have priveleged EXEC  access to the switch:

. Push and hold the _Reset_ button with sharp object like pen/pencil.
. Now also push and hold _Clear_ button with another sharp object.
. When LEDs are turned on - release _Reset_ button, while holding the _Clear_.
. When LEDs start to blink, release the _Clear_ button as well.

If you have privileged EXEC access to the switch, just run *(config)# erase startup* and reboot. 

== Restrict management access to specific IP addresses
To limit access to the switch, use *ip authorized-managers* command. Example - limit access to a single IP of 192.168.13.127:

----
ip authorized-managers 192.168.13.127 255.255.255.255 access operator
ip authorized-managers 192.168.13.127 255.255.255.255 access manager
----


== Add default gateway on Layer 2 switch for management
We have to set default gateway on a switch for the management VLAN we choose to be reachable and managed remotely. The command does not mention explicitly the VLAN number, just make sure the network is the network configured on the management VLAN.

----
ip default-gateway 10.13.13.127
----

It is, for example, when VLAN 200 is configured as management VLAN:

----
vlan 200
   name "MgmtVlan"
   tagged Trk1
   ip address 10.13.13.250 255.255.255.0
   exit
----


