= RAD ETX 203, 205, 220 debug and information commands

Author: Yuri Slobodyanyuk, https://www.linkedin.com/in/yurislobodyanyuk/

Carrier Ethernet Devices by RAD (ETX-203AX, ETX-203AM, ETX-203AX-T, ETX-205A, ETX-220A) are quite popular with telco companies around the world for connecting end clients to the backbone at layer 2. And while reference documentation is available, I couldn't find the debug/information commands digest on the Internet at all. This post, I hope, comes to fill the gap.

The commands below are meant to be run on the device CLI itself, not on provisioning system like RADview. You can see how output looks like when run on the real ETX on my blog post https://yurisk.info/2020/03/21/rad-etx-203-203-220-debug-and-information-commands-examples/.


[cols=2*,options="header"]
|===
|Command
|Description


|*show configure port summary*
| Show port summary: state (up/down), speed

|*show config port _name_ status*
| Show port status: administrative and operational states, speed/duplex, connector type, MAC address, and most important (for fiber) - RX/TX signal power (dBm)

|*show config port _name_ statistics*
| Statistics of the port: total bits/frames passed, maximum/minimum bits/sec seen, and most
interesting - CRC errors, error frames, oversize frames, discards, CV/ES/SES/FC stats for
E1 lines.


|*config port ethernet _number_*

*clear-statistics*
|Clear all statistics/counters for this port.

|*config flow*

*flow _flow-name_*

*show statistics running*
|Show detailed counters for the given flow, will include `bps`, max/min `bps` seen after reboot, `drops` if any.


|*config port _name_*  

*rate-measure interval _seconds_*  

*show rate*
| Show port utilization in bits/sec in real-time


|_Responder:_

*config flow*  

*service-ping-response local-ip 13.13.13.2/30 next-hop 13.13.13.1 egress-port ethernet 4/2 vlan 777*

_Ping sender:_

*config flow*

service-ping local-ip 13.13.13.1/30 dst-ip 13.13.13.2 next-hop 13.13.13.2 egress-port ethernet 4/1 vlan 777 number-of-packets 10 payload-size 1450

|Send ping over the client vlan in Service Provider network (here 777) from ETX
to ETX to measure latency and packet loss. You configure one ETX as a responder
and another one as a sender.

|*show configure flows summary brief*
|List all flows configured on this ETX briefly

|*show configure flows summary details*
|List all flows configured on this ETX with details

|*config flow _name_*

*mac-learning*

*show mac-table*

*no mac-learning*
|Enable MAC address learning inside a flow and show the MAC table. The _flow_ should be the one where
those MAC addresses are supposed to be learned, and in the appropriate
direction. E.g. if the equipment of the end client is connected to ETX port
`ethernet 0/10`, then you should run this command under the flow that has 
`ingress port 0/10`, to see if the ETX can see client's equipment. WARNING:
after showing the results, make sure to disable the MAC learning, as it may
interfere with the client's traffic. 
 
|*show config system system-date*
| Show system time of the appliance, important for logs/alarms correlation.

|*show config reporting brief-alarm-log*
|Show alarms log, their severity/state/last raised time


|*exit all*
|Exit all sub-configuration modes to the top level.

|*show file startup*
|Show startup configuration.

|*save*
|Save the configuration.

|*clear-statistics*
|Clear all statistics (at the highest config level) - errors on interfaces, bytes sent/received, etc.

|*admin*

*reboot*
|Reboot the device.


|===
